# Classes of Random Events

## Sample space and Event

Let $\Omega$ (the **sample space** of all possible outcomes of an experiments) be an arbitrary non-empty set. Its elements, denoted by $\omega$, will be interpreted as **outcomes (results)** of some experiment. These outcomes sometimes called **simple events** or **elements** becaus they cannot be decomposed further. Other events (subsets of $\Omega$) are **compound events** because they are composed of two or more simple events. An **event** $A$ occurs if and only if the randomly selected $\omega$ belongs to $A$. As usual, we use $A \cup B$ and $A \cap B$ to represent the union and the intersection of any two subsets $A$ and $B$ of $\Omega$, respectively. Also, $A^c$ is the complement of $A\subset \Omega$. In particular, $\Omega^c=\theta$, where $\theta$ is the empty set.

```{example, name="an example of sample space and event"}
When drawing randomly from $[0,1]$ the sample space is $\Omega = [0,1]$, each $\omega \in [0,1]$ is a sample event, and the interval $A=(\frac{1}{2},1]$ is an example of a compound event.

```

## Field and sigma-field

```{definition, name="Field"}
The class $\mathcal{A}$ of subsets of $\Omega$ is called a **field** if it contains $\Omega$ and is closed under the formation of complements and finite unions, that is if:
  
1. $\Omega \in \mathcal{A}$;

2. $A \in \mathcal{A} \Rightarrow A^c \in \mathcal{A}$;

3. $A_{1}, A_{2}\in\mathcal{A} \Rightarrow A_{1} \cup A_{2} \in \mathcal{A}$.

```

```{proposition, name="Definition of a field"}
The condition 3 of the definition of a field can be replaced by

3. $A_{1}, A_{2} \in \mathcal{A} \Rightarrow A_{1} \cap A_{2} \in \mathcal{A}$.

That means, $\mathcal{A}$ is closed under finite intersections.

```

```{proof}
By de Morgan laws, $(A_{1} \cap A_{2})^{C} = A_{1}^{C} \cup A_{2}^{C}$ and $(A_{1} \cup A_{2})^{c} = A_{1}^{C} \cap A_{2}^{C}$. By the condition 2 of the definition of a field, we can get the desired result.

```

```{exercise}
Which of the followings are $\sigma$-fields of subsets of $\Omega=\{1,2,3,4,5,6\}?$

a) $\{ \{1,2,\}, \{1,2,3,\}, \{4,5,6\}, \emptyset, \Omega \}$.

b) $\{ \{1,2\}, \{3,4,5,6\}, \emptyset, \Omega  \}$.

c) $\{ \{1\}, \{3,4,5,6\}, \{1,3,4,5,6\},\Omega \}$.

```

```{solution}
b.

```

```{definition, name="Semi-field"}
Let $\Omega$ be an arbitrary set. A non-empty class $\mathcal{J}$ of subsets of $\Omega$ is called a **semi-field** if $\Omega = \mathcal{J}, \emptyset \in \mathcal{J}$, $\mathcal{J}$ is closed under the formation of finite intersections, and the complement of any set in $\mathcal{J}$ is a finite sum of disjoint sets of $\mathcal{J}$.

```

It is easy to see that any field of subsets of $\Omega$ is also a semi-field. However, the following simple examples show that the converse is not true.

```{example, name="A class of events which is a semi-field but not a field"}
1. Let $\Omega=[-\infty, \infty)$ and $\mathcal{J}_{1}$, contain $\Omega$, $\{\infty\}$ and all intervals of the type $[a,b)$ where $-\infty < a \leq b \leq \infty$. Then, $\emptyset \in \mathcal{J}_{1}$, $\Omega \in \mathcal{J}_{1}$, $[a_{1}, b_{1}) \cap [a_{2}, b_{2})=[a_{1} \vee a_{2}, b_{1} \wedge b_{2})\in\mathcal{J}_{1}$, and $[a,b)^{C}=[-\infty, a)\cup[b, \infty)$. So, $\mathcal{J}_{1}$, is a semi-field. Obviously $\mathcal{J}_{1}$ is not a field (Check \@ref(exm:efnsf)).

2. Take $\Omega = \mathbb{R}^{1}$ and denote by $\mathcal{J}_{2}$ the class of all subsets of the form $A\cap B$ where $A$ is closed and $B$ is an open set in $\Omega$. Then again, $\mathcal{J}_{2}$ is a semi-field but not a field.

```

```{definition, name="Sigma-field"}
The class $\mathcal{F}$ of subsets of $\Omega$ is called a $\sigma$**-field** if it is a field and closed under the formation of countable unions, that is if:
  
4. $A_{1}, A_{2}, \ldots, \in \mathcal{F} \Rightarrow \cup_{n=1}^{\infty}A_{n} \in \mathcal{F}$.

```

```{proposition, name="Definition of a sigma-field", label="sigmafield"}
The condition 4 of the definition of a sigma-field can be replaced by

4. $A_{1}, A_{2}, \ldots, \in \mathcal{F} \Rightarrow \cap_{n=1}^{\infty}A_{n} \in \mathcal{F}$.

That means, $\sigma$-field $\mathcal{F}$ is closed under countable intersections because $\bigcap_{n=1}^{\infty}A_{n} = (\cup_{n=1}^{\infty}A_{n}^{C})^{C}$ and each $A_{n}^{C}$ belongs to $\mathcal{F}$.

```

```{proof}
By de Morgan laws and condition 2 of the definition of a field, $(\cap_{n=1}^{\infty}A_{n})^{C}=\cup_{n=1}^{\infty}A_{n}^{C}\in\mathcal{F}$ and $(\cup_{n=1}^{\infty}A_{n})^{C}=\cap_{n=1}^{\infty}A_{n}^{C}\in\mathcal{F}$. So, we can change the condition 4.

```

Usually, $\mathcal{F}$ is the set of events (subsets of $\Omega$) we are allowed to consider.

```{definition, name="Random events (events)"}
The elements of any field of $\sigma$-field are called **random events** (or simply, **events**).

```

```{example, name="A class of events which is a field but not a sigma-field", label="efnsf"}
Let $\Omega = [0, \infty)$ and $\mathcal{F}_{1}$ be the class of all intervals of the type $[a,b)$ or $[a,\infty)$, where $0 \leq a < b < \infty$. Let $\mathcal{F}_{2}$ be the class of all finite sums of intervals of $\mathcal{F}_{1}$. Then $\mathcal{F}_{1}$ is not a field, and $\mathcal{F}_{2}$ is a field but not a $\sigma$-field.

Take arbitrary numbers $a$ and $b$, $0<a<b<\infty$. Then $A=[a,b)\in \mathcal{F}_{1}$. However, $A^{C} = [0, a) \cup [b, \infty)\neq \mathcal{F}_{1}$ and thus $\mathcal{F}_{1}$ is not a field.

It is easy to see that

1. the finite union of finite sums of intervals (of $\mathcal{F}_{1}$) is again a sum of intervals;

2. the complement of a finite sum of intervals is also a sum of intervals. This means that $\mathcal{F}_{2}$ is a field.

However, $\mathcal{F}_{2}$ is not a $\sigma$-field because, for example, the set $A_{n} =[0,\frac{1}{n})\in\mathcal{F}_{1}$ for each $n=1,2,\ldots,$ and the intersection $\bigcap_{n=1}^{\infty}A_{n} =\{0\}$ does not belong to $\mathcal{F}_{1}$.

Let us look at two additional cases.

1. Let $\Omega = \mathbb{R}^{1}$ and $\mathcal{F}$ be the class of all finite sums of intervals of the type $(-\infty, a], $(b,c]$ and $(d,\infty)$. Then $\mathcal{F}$ is a field. But the intersection $\cap_{n=1}^{\infty}(b-\frac{1}{n}, c]$ is equal to $[b,c]$ which does not belong to $\mathcal{F}$. Hence, the field $\mathcal{F}$ is not a $\sigma$-field.

2. Let $\Omega$ be any infinite set and $\mathcal{A}$ the collection of all subsets $A\in \Omega$ such that either $A$ or $A^{c}$ is finite. Then it is easy to see that $\mathcal{A}$ is a field but not a $\sigma$-field.

```

```{example, name="A class of events can be closed under finite unions and finite intersections but not under complements"}
Let $\Omega = \mathbb{R}$ and the class $\mathcal{A}$ consist of intervals of the type $(x,\infty)$, $x\in\Omega$. Then using the notations $u = x\wedge y:= \min\{x,y\}$ and $v=x\vee y:=\max \{x,y\}$ we have:
$$(x,\infty) \cup (y,\infty) = (u,\infty)\in\mathcal{A}$$
$$(x,\infty) \cap (y,\infty) = (v,\infty)\in\mathcal{A}.$$
However, $(x,\infty)^{C} = (-\infty, x]\notin\mathcal{A}$.

```

```{remark}
Because any field or $\sigma$-field $\mathcal{F}$ is nonempty, it contains a set $A$, and therefore $A^{C}$. Consequently, any field or $\sigma$-field contains $\Omega = A \cup A^{C}$ and $\emptyset = \Omega^{C}$.

```

A $\sigma$-field is more restrictive than a field. Because we want to be able to consider countable unions, we require the allowable sets $\mathcal{F}$ to be a $\sigma$-field. Therefore, it is understood in probability theory and throughout the remainder we are allowed to consider only the events belonging to the $\sigma$-field $\mathcal{F}$. We will see that fields also play an important role in probability because a common technique is first to define a probability measure on a field and then extend it to a $\sigma$-field.

```{definition, name="D-system"}
A system $\mathcal{D}$ of subsets of a given set $\Omega$ is called a **D-system** (Dynkin system) in $\Omega$ if the following three conditions hold:
  
1. $\Omega \in \mathcal{D}$;

2. $A,B\in \mathcal{D}$ and $A\subset B \Rightarrow B\backslash A\in\mathcal{D}$;

3. $A_{n}\in \mathcal{D}, n=1,2,\ldots .$ and $A_{1} \subset A_{2} \subset \ldots \Rightarrow \cup_{n=1}^{\infty}A_{n} \in \mathcal{D}$.

```

It is obvious that every $\sigma$-field is a D-system, but the converse may not be true.

```{example, name="Every sigma-field of events is a D-system, but the converse does not always hold"}
Take $\Omega = \{\omega_{1}, \omega_{2}, \ldots, \omega_{2n}\}, n\in\mathbb{N}$. Denote by $\mathcal{D}_{e}$ the collection of all subsets $D\in\Omega$ consisting of an even number of elements. Conditions 1, 2, and 3 above are satisfied, and hence $\mathcal{D}_{e}$ is a D-system. However, if $n<1$ and we take $A=\{\omega_{1}, \omega_{2}\}$ and $B=\{\omega_{2}, \omega_{3}\}$, we see that $A\in\mathcal{D}_{e}, B\in \mathcal{D}_{e}$ and $A\cap B =\{\omega_{2}\}\notin \mathcal{D}_{e}$. Thus $\mathcal{D}_{e}$ is not even a field and hence not a $\sigma$-field.

```

Note that a D-system $\mathcal{D}$ is a $\sigma$-field if and only if the intersection of any two sets in $\mathcal{D}$ is again in $\mathcal{D}$.

```{example, name="Trivial and total sigma-fields"}
For any sample space $\Omega$, the smallest and largest $\sigma$-fields are the **trivial** $\sigma$**-field** $2^{\Omega}=\{\emptyset, \Omega\}$ and the **total** $\sigma$**-field** (also called the power $\sigma$-field) $(\Omega)=\{ \text{all subsets of } \Omega \}$, respectively.

```

Remember that we are allowed to determine only whether or not event $A$ occured for $A\in \mathcal{F}$, not for sets outside $\mathcal{F}$. The trivial $\sigma$-field is not very useful because the only events that we are allowed to consider are the entire sample space and the empty set. In other words, we can determine only whether something or nothing happened. With the total $\sigma$-field we can determine, for each subset $A\subset \Omega$, whether or not event $A$ occurred. The trouble with $2^{\Omega}$ is that it may be too large to ensure that the properties we desire for a probability measure hold for all $A\in\mathcal{F}$.

Therefore, we want $\mathcal{F}$ to be large, but not too large.

```{example, name="For countable sample space, the sigma-field should be the total sigma-field"}
Suppose $\Omega$ is a countable set like $\{0,1,2,\ldots, \}$. We certainly want $\mathcal{F}$ to contain each singleton. But any $\sigma$-field that contains each singleton $\omega$ must contain all subsets of $\Omega$. This follows from the fact that any subset $A$ of $\Omega$ is a countable union $\cup_{n=1}^{\infty}\{\omega_{i}\}$ of singletons, and $\sigma$-fields are closed under countable unions. Therefore, when the sample space is countable, we should always use the total $\sigma$-field.

```

```{proposition, name="The intersection of sigma-fields are sigma-fields"}
The intersection $\bigcap_{t} \mathcal{F}_{t}$ of any collection of $\sigma$-fields of $\Omega$ is a $\sigma$-field.

```

```{proof}
Note that $\mathcal{F}$ is nonempty, because $\emptyset \in \mathcal{F}_{t}$ and $\Omega\in \mathcal{F}_{t}$ for each $t$, and therefore $\emptyset$ and $\Omega$ belong to $\mathcal{F} = \bigcap_{t}\mathcal{F}$. Also, if $A\in\mathcal{F}$, then $A$ belongs to each $\mathcal{F}_{t}$. Thus, $A^{C}$ belongs to each $\mathcal{F}_{t}$, and therefore $\mathcal{F}=\bigcap_{t}\mathcal{F}_{t}$. Similarly, if $A_{1}, A_{2},\ldots$ belong to each $\mathcal{F}_{t}$, then $A=\bigcup_{i=1}^{\infty}A_{i}$ also belongs to each $\mathcal{F}_{t}$, so $A$ belongs to $\mathcal{F}=\bigcap_{t}\mathcal{F}_{t}$. It follows that $\mathcal{F}$ is a $\sigma$-field.

```

```{example, name="The union of a sequence of sigma-fields need not be a sigma-field"}
Let $\mathcal{F}_{1},\mathcal{F}_{2}, \ldots$ be a sequence of $\sigma$-fields of subsets of the set $\Omega$. Then their intersection $\bigcap_{n=1}^{\infty} \mathcal{F}_{n}$ is always a $\sigma$-field and it is natural to ask whether the union $\bigcup_{n=1}^{\infty}\mathcal{F}_{n}$ is a $\sigma$-field. We shall now show that the answer to this question is negative.

Consider the set $\Omega=\{\omega_{1},\omega_{2},\omega_{3}\}$ and the following two classes of its subsets: $\mathcal{F}_{1}=\{\emptyset, \{\omega_{1}\}, \{\omega_{2},\omega_{3}\}, \Omega \}$, $\mathcal{F}_{2}=\{\emptyset, \{\omega_{2}\}, \{\omega_{1},\omega_{3}\}, \Omega \}.$ Then $\mathcal{F}_{1}$ and $\mathcal{F}_{2}$ are fields and hence $\sigma$-fields. Obviously the intersection $\mathcal{F}_{1}\cap \mathcal{F}_{2} =\{ \emptyset, \Omega \}$, the trivial $\sigma$-field. However, the union

\begin{align*}
\mathcal{F}&=\mathcal{F}_{1} \cup \mathcal{F}_{2}\\
&= \{\emptyset, \{\omega_{1}\}, \{\omega_{2}\}, \{\omega_{2},\omega_{3} \}, \{\omega_{1},\omega_{3} \},\Omega \}\\
\end{align*}
  
is not a field, and hence not a $\sigma$-field because the element $\{\omega_{1}\}\cup \{\omega_{2}\}=\{\omega_{1},\omega_{2}\}\notin\mathcal{F}$.

```

## Sigma-fields in real line

We next consider $\sigma$-fields when $\Omega$ is the uncountable set $\mathbb{R}$ (or an interval). Again, any useful $\sigma$-field must contain each singleton $\omega$.

```{definition, name="Co-finite and co-countable"}
The set $A\in\Omega$ is called **co-finite** set if its complement $A^C$ is finnite. Further, the set $A\in\Omega$ is called a **co-countable** set if $A^C$ is countable.

```

Let $\mathcal{F}_{1}$ consist of the finite and co-finite subsets of $\Omega$. Then, $\mathcal{F}_{1}$ is a field. It is a $\sigma$-field if and only if $\Omega$ is finite. Let $\mathcal{F}_{2}$ consist of the countable and the co-countable subsets of $\Omega$. Then it is easy to check that $\mathcal{F}_{2}$ is a $\sigma$-field. 

```{exercise}
Prove that the collection of countable and co-countable sets is itself a $\sigma$-field.

```

```{example, name="A sigma-field of subsets of sample space need not contain all subsets of sample space"}
Suppose that $\Omega$ is uncountable. Then $\Omega$ contains a subset $A$ such that $A$ and $A^C$ are both uncountable. This show that in general a $\sigma$-field of $\Omega$ need not contain all subsets of $\Omega$ and need not be closed under the formation of arbitrary uncountable unions.

```

```{example, name="Sigma-field of countable and co-countable sets: too small"}
Suppose that $\Omega$ is uncountable set like $\mathbb{R}$ or $[0,1]$. If we want $\mathcal{F}$ to include each singleton $\omega$, then $\mathcal{F}$ must contain each countable subset $A$. It must also contain the complement of each countable set. Therefore, any $\sigma$-field containing the singletons must contain all countable and co-countable sets. Unfortunately, this $\sigma$-field is not large enough to be useful. For instance, if $\Omega=[0,1]$, then we are not allowed to consider events like $[0,\frac{1}{2}]$ because it is neither countable nor co-countable.

```

We continue our quest for the smalles $\sigma$-field that contains all of the "useful" subsets of the uncountable set $\mathbb{R}$. We have seen that the collection of countable and co-countable sets is not a good choice because it excludes common sets like $[0,\frac{1}{2}]$. We certainly want $\mathcal{F}$ to include all intervals. But remember that we do not want $\mathcal{F}$ to be too large, else it might contain "pathological sets" that cause probability to behave strangely. Therefore, we would like to find the **smallest** $\sigma$-field $\mathcal{F}$ that contains all of the intervals. That is, we want $\mathcal{F}$ to contain all intervals, and if $\mathcal{G}$ is any other $\sigma$-field containing the intervals, then $\mathcal{F}\subset\mathcal{G}$. The smallest $\sigma$-field containing a collection $\mathcal{A}$, denoted $\sigma(\mathcal{A})$, is called the **sigma-field generated by** $\mathcal{A}$. We want to find $\sigma(\text{intervals})$. Any $\sigma$-field containing the intervals must also contain all finite unions of disjoint sets of the form $(a,b]$, $(-\infty, a]$, or $(b,\infty)$. Therefore, if this latter collection is a $\sigma$-field, it must be $\sigma(\text{intervals})$. Unfortunately, it is not a $\sigma$-field.

```{exercise}
If \mathcal{A} is a $\sigma$-field, then $\sigma(\mathcal{A})=\mathcal{A}$.

```

```{example, name="Very important field"}
If $\Omega =\mathbb{R}$, the collection $\mathcal{F}_{0}$ of finite unions of disjoint sets of the form $(a,b]$, $(-\infty,a]$, or $(b,\infty)$ is a field, but not a $\sigma$-field. It generates $\sigma(\text{intervals})$.

```

```{exercise}
Prove the above example.

```

Continuing aour search for $\sigma(\text{intervals})$, consider the collection $\{\mathcal{F}_{t}\}_{t\in T}$ of all $\sigma$-fields containing the intervals. There are at least one, namely the total $\sigma$-field $2^{\mathbb{R}}$ of all subsets of the line. Let $\mathcal{F} = \bigcap_{t}\mathcal{F}_{t}$. We claim that $\mathcal{F}=\sigma(\text{intervals})$. We need only show that $\mathcal{F}$ is a $\sigma$-field, because any other $\sigma$-field containing the intervals clearly contains $\mathcal{F}$.

## Borel sigma-field

```{definition, name="1-dimensional Borel sigma-field"}
The smallest $\sigma$-field containing the intervals of $\mathbb{R}$, namely the intersection of all $\sigma$-fields containing the intervals, is called the **Borel sigma-field** and denoted $\mathcal{B}$ or $\mathcal{B}^{1}$. The sets in $\mathcal{B}$ are called **Borel sets**. The Borel sets of $\mathbb{R}$ that are subsets of $[0,1]$ are denoted $\mathcal{B}_{[0,1]}$.

```

The definition of the Borel $\sigma$-field is somewhat dissatisfying because it is hard to picture the intersection of all $\sigma$-fields containing the intervals. It would be more pleasing if we could begin with the intervals $\mathcal{I}_1$, throw in all complements and countable unions of sets in $\mathcal{I}_{1}$ to create $\mathcal{I}_{2}$, then throw in all complements and countable unions of sets in $\mathcal{I}_{2}$ to create $\mathcal{I}_{3}$, etc. It would still be difficult to picture all of the sets, but at least we could imagine how to construct them. Unfortunately, this process must be continued indefinitely. In fact, even $\bigcup_{i=1}^{\infty}\mathcal{I}_{i}$ does not produce all of the Borel sets. [@Billingsley2012]

```{remark, name="The Bore sigma-field is very broad"}
The Borel $\sigma$-field contains many sets other than intervals, including, for example:

1. Countable unions of intervals, and therefore all open sets by (Proposition A.15.)

2. All closed sets by part 1 and the fact that complements of sets in $\mathcal{B}$ are in $\mathcal{B}$.

3. The rational numbers by part 2 because each rational $r$ is a closed set (it is easy to see that its complement is open), and the set of rational numbers is a countable union of these closed sets.

4. The irrational numbers, being the complement of the Borel set of rational numbers.

```

It is actually difficult to construct a set that is **not a Borel set**. Nevertheless, we will see later that an even larger $\sigma$-field, called the **Lebesgue sets**, is also useful in probability and measure theory.

It is sometimes helpful to consider the events $\{-\infty\}$ or $\{+\infty\}$. These sets are not in the Borel $\sigma$-field because they are not subsets of $\mathbb{R} = (-\infty, \infty)$. To consider them as events, we must extend the real line by augmenting it with $\{-\infty, +\infty\}$.

```{definition, name="Extended line and extended intervals"}
The **extended line** $\bar{\mathbb{R}}$ is $[-\infty, \infty]$, meaning $(-\infty, \infty)\cup \{-\infty, \infty \}$. An extended interval is of the form $[x,y]$, $[x,y)$, $(x,y]$, or $(x,y)$, where $x$ or $y$ can be numbers or $\pm \infty$; $[a,\infty]$ means $[a,\infty)\cup \{\infty\}$, $[-\infty, b]$ means $(-\infty, b] \cup \{-\infty\}$, etc.

```

When considering $\bar{\mathbb{R}}$ instead of $\mathbb{R}$, we must remember to take complements with respect to $\mathbb{R}$. For instance, the complement of $(0,1]$ is $\bar{\mathbb{R}}\backslash (0,1] = [-\infty, 0]\cup (1,\infty]$, and the complement of $\mathbb{R}=(-\infty, \infty)$ is $\bar{\mathbb{R}}\backslash\mathbb{R} =\{-\infty, \infty\}$.

```{definition, name="Extended Borel sigma-field"}
The extended Borel $\sigma$-field $\bar{\mathcal{B}}$ is the smallest $\sigma$-field of subsets of $\bar{\mathbb{R}}$ that contains all of the extended intervals.

```

```{proposition, name="Equivalent formulations of extended Borel sigma-field"}
The flollowing are equivalent.

1. $\bar{\mathcal{B}}$ is the extended Borel $\sigma$-field.

2. $\bar{\mathcal{B}}$ is the smallest $\sigma$-field that contains the two sets $\{-\infty\}$ and $\{+\infty\}$ and all Borel subsets of $\mathbb{R}$.

3. $\bar{\mathcal{B}}$ consists of all Borel subsets $\mathcal{B}$ of $\mathbb{R}$, together with all augumentations $\bar{mathcal{B}}$ of $\mathcal{B}$ by $-\infty$, $\infty$, or both.

```

```{exercise}
Prove the above proposition.

```

## High-dimensional sigmal fields

## Infinitely often event

IF $\{A_n\}\in\mathcal{F}$, we can define other events involving the $A_{n}$. We have seen, for example, that $B=\cup_{n=1}^{\infty}A_{n}$ is the event that at least one $A_n$ occurs, while $C=\cap_{n=1}^{\infty}A_n$ is the event that all of the $A_n$ occur. Sometimes there is interest in seeing whether $A_n$ occurs for infinitely many $n$. For instance, in a coin-flipping experiment, let $A_n$ denote the event that the $n$-th coin flip is heads. We might be interested in whether infinitely many flips are heads. We now show that for general $A_1, A_2,\ldots,$ the event that $A_n$ occurs for infinitely many $n$ is a honest (bona fide) event in the sense that it is in $\mathcal{F}$. Note that $\omega \in A_{n}$ for infinitely many $n$ if and only if no matter how large $N$ i, $\omega\in \cap_{N=1}^{\infty}\cup_{n\geq N}A_{n} =\cap_{N=1}^{\infty} B_{N}$, where $B_{N} =\cup_{n\geq N } A_{n}$. Because $B_N$ is a countalbe union of $\mathcal{F}$-sets, $B_N\in\mathcal{F}$. This being true for each $N$, $\cap_{N=1}^{\infty} B_{N} \in\mathcal{F}$ because $\mathcal{F}$ is closed under countable intersections. (refer to Prop \@ref(prp:sigmafield)) Therefore, the event that $A_n$ occurs for infinitely many $n$ is in $\mathcal{F}$. We denote this event by $\{A_n \text{ i.o}\}$, which stands for $A_n$ occurs infinitely often (in $n$).


```{proposition, name="The infinitely often event is in sigma-field."}
If $A_n\in\mathcal{F}$ for $n=1,2,\ldots,$ the event $\{A_n \text{ i.o}\}$, namely $\cap_{N=1}^{\infty}\cup_{n\geq N}A_{n}$ is in $\mathcal{F}$.

```

```{remark}
The complement of $\{A_n \text{ i.o}\}$, namely that $A_n$ occurs only finitely often, is also in $\mathcal{F}$ because $\mathcal{F}$ is closed under complementation. This event is, by De Morgan's laws, $\{\cap_{N=1}^{\infty}\cup_{n\geq N} A_n \}^{C} = \cup_{N=1}^{\infty}B_{N}^{C} = \cup_{N=1}^{\infty}\cap_{n\geq N} A_{n}^{C}$.

This expression can also be deduced from general principles because if $\omega$ is in only finitely many of the $A_n$, then there must be an $N$ for which $\omega$ is not in $A_{n}$ for any $n\geq N$. That is, $\omega$ must be in $A_{n}^{C}$ for all $n\geq N$. This must occur for at least on $N$, which translates into a union. Thus again we arrive at the expression $\cup_{N=1}^{\infty}\cap_{n\geq N}A_{n}^{C}$ for the event that $A_{n}$ occurs only finitely often.

```
